# Copyright © 2013, Qball Cow and contributors
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
# 
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#       
#     * Neither the name of Qball Cow nor the
#       names of contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY Qball Cow ''AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL Qball Cow BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

NOTE_RESET="\e[0m"
NOTE_BOLD="\e[1m"
NOTE_COLOR_BLACK="\e[0;30m"
NOTE_COLOR_RED="\e[0;31m"
NOTE_COLOR_GREEN="\e[0;32m"
NOTE_COLOR_YELLOW="\e[0;33m"
NOTE_COLOR_BLUE="\e[0;34m"
NOTE_COLOR_MAGENTA="\e[0;35m"
NOTE_COLOR_CYAN="\e[0;36m"
NOTE_COLOR_WHITE="\e[0;37m"
NOTE_COLOR_WHITE_BOLD="\e[1;37m"
NOTE_COLOR_BLACK_BOLD="\e[1;30m"
NOTE_COLOR_RED_BOLD="\e[1;31m"
NOTE_COLOR_GREEN_BOLD="\e[1;32m"
NOTE_COLOR_YELLOW_BOLD="\e[1;33m"
NOTE_COLOR_BLUE_BOLD="\e[1;34m"
NOTE_COLOR_MAGENTA_BOLD="\e[1;35m"
NOTE_COLOR_CYAN_BOLD="\e[1;36m"
NOTE_UNDERLINE="\033[4m"
